Add controllers
pnikishechkin/java-shareit pull request #1
Opened 2024-09-29 11:14 UTC by pnikishechkin

2024-09-30 12:48 UTC, tomattman requested changes
Привет, отличная работа, есть пара моментов на улучшение

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    HashMap<Integer, Item> items = new HashMap<>();
модификаторы доступа

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    HashMap<Integer, Set<Item>> usersItems = new HashMap<>();
можно было бы реализовать через итерацию по всем айтемам и фильтрацией по userID 
не за чем дублировать данные, может создать лишних проблем в синхронизации данных

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotNull
обычно на поля в модели уже не вешают валидационные аннотации, хватает валидации на уровне DTO и базы данных

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static Item mapToItemDto(ItemCreateDto itemCreateDto) {
можно методы в маппере называть проще toDto и toEntity 
а еще рекомендую перегрузить эти методы, на прием в качетсве параметра коллекций, так получится что всем маппингом будет заниматься только маппер, и не придётся итерироваться по обьектам и мапить в других местах

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static Item mapToItemDto(ItemCreateDto itemCreateDto) {
то же касается остальных мапперов

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    HashMap<Integer, User> users = new HashMap<>();
снова модификаторы

2024-09-30 12:48 UTC, tomattman commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    Set<String> emails = new HashSet<>();
снова дублицирование данных, рекомендую убрать его

2024-10-01 14:06 UTC, pnikishechkin commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    HashMap<Integer, Set<Item>> usersItems = new HashMap<>();
Да, можно пробегать по всем item и искать userID, но нам на вебинаре объясняли, что получение всех предметов должно осуществляться за O(1), и для этого можно создать вторую хеш-таблицу. Где правда?)

2024-10-01 14:12 UTC, pnikishechkin commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    Set<String> emails = new HashSet<>();
Ну это же дублирование ссылок на объекты? Здесь та же ситуация, такой подход предложил наставник, для быстрого определения дубляжей e-mail, чтобы не пробегать по всем.
Как сделать лучше?

2024-10-01 18:14 UTC, tomattman commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    HashMap<Integer, Set<Item>> usersItems = new HashMap<>();
все очень зависит от требований
обычно сложность бывает не только по количеству операций, но и по задействованной памяти, и чаще всего теряется в одном выигрывается в другом
конкертно в этом случае совершенно без разницы, но когда данные дублируются становится тяжелее поддерживать их целостность

2024-10-01 18:16 UTC, tomattman commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    Set<String> emails = new HashSet<>();
как уже написал выше, в зависимости от того, чего ты хочешь добиться?
на этапе учебного задания важнее что понимаешь зачем это делаешь, и плюсы и минусы данного подхода

2024-10-01 18:16 UTC, tomattman approved these changes
Принято

2024-10-02 06:34 UTC, pnikishechkin commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    HashMap<Integer, Set<Item>> usersItems = new HashMap<>();
Спасибо за пояснение

2024-10-02 06:34 UTC, merged